name: Run_Collection
on:
  workflow_dispatch:
jobs:
  test-api:
    runs-on: ubuntu-latest  # Specify a valid runner environment here
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install newman
        run: |
          npm install -g newman

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run Pet Circle collection in newman
        run: |
          newman run pet_circle.postman_collection.json -e pet_circle.postman_environment.json --delay-request 500 --verbose